version: "2" 
# Definir version de compose: Instalada v2.17.3
services:
  # servicios define que imagenes se van a instalar Mysql + Wordpress Combo
  db:
    image: mysql:8.0
    # imagen TAG:8.0 requerida por Proyecto
    restart: unless-stopped   # Se reinicia siempre a menos que se detenga manualmente
    environment:
      MYSQL_ROOT_PASSWORD: myrootpwd
      MYSQL_DATABASE: dockerwpdb
      MYSQL_USER: dockerwpuser
      MYSQL_PASSWORD: dockersqlpwd
      # Definicion de Base se datos
  wordpress:
    depends_on:
      - db
    image: wordpress:6.2-php8.0-apache
    # Imagen TAG: Requerido 6.2.0 Por Proyecto
    restart: unless-stopped   # Se reinicia siempre a menos que se detenga manualmente
    # Restart always. Si Cae el contenedor se reinicia
    ports:
      - "8000:80"
      # Verificar proyecto en http://localhost:8000
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: dockerwpuser
      WORDPRESS_DB_PASSWORD: dockersqlpwd
      WORDPRESS_DB_NAME: dockerwpdb
      # Definiciones de WordPress
    volumes:
      ["./:/var/www/html"]

  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        ports:
            - "4283:80"
        environment:
            PMA_HOST: db:3306  
            MYSQL_ROOT_PASSWORD: myrootpwd
        depends_on:
            - db
                
volumes:
  mysql: {}
